server:
  port: 8099
#spring:
#  security:
#    user:
#      name: user
#      password: user
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver