server:
  port: 8099
#spring:
#  security:
#    user:
#      name: user
#      password: user
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.126.78.207:3306/graduate?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: gistone1234
  redis:
    host: 112.126.78.207
    port: 6379
    database: 0